[project]
name = "mhloadout-plugin"

[target.reframework]
type = "interface"
include-directories = ["deps/reframework/include"]

[target.lua]
type = "static"
sources = ["deps/lua/src/*.c"]
include-directories = ["deps/lua/src"]

[target.sol2]
type = "interface"
include-directories = ["deps/sol2/single/include"]

[fetch-content.cpr]
cmake-before = """
set(BUILD_SHARED_LIBS_BACKUP BUILD_SHARED_LIBS) # Backup old variable
set(BUILD_SHARED_LIBS OFF)
"""
cmake-after = """
set(BUILD_SHARED_LIBS BUILD_SHARED_LIBS_BACKUP) # Restore old variable
"""
git = "https://github.com/libcpr/cpr"
tag = "a2d35a1cb9f3f7e2f1469d6a189751331dc99f96"

[target.mhloadout-plugin]
type = "shared"
sources = ["src/**.cpp"]
headers = ["src/**.hpp"]
link-libraries = ["reframework", "lua", "sol2", "cpr::cpr"]
compile-features = ["cxx_std_20"]